### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by drmason789** [leibnitz27/olewoo#8]
This would be convienient for including olewoo in a build process. Currently I have an executable committed to a folder which is called by a build script.

I'm willing to do this at some point and submit a pull request.

**Comment by bclothier** [comment]
FWIW that would be a huge improvement but I want to ask questions and point out some things to consider to clarify what should be in the scope.

First, it should be noted that olewoo originally was made as a replacement for oleview. It wasn't originally designed for the purpose of generating IDL files that could be then compiled. Until I came and hacked things up. 😄 

Currently, we have a project that uses olewoo as part of the build, manipulating the IDL. Right now it's very hacky and involves injecting the modifications into a generated IDL from a tlb, which is very roundabout way of doing things. I only did that way because I was too lazy to properly implement a process that would be able to generate a type library directly. Here's an example of how it's currently [generated](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Deployment.Build/IdlGeneration/IdlGenerator.cs#L32) and [modified](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Deployment.Build/IdlGeneration/IdlListener.cs). It's important to note that all this hinges on the use of [highlighted methods](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Deployment.Build/IdlGeneration/IdlGenerator.cs#L34-L37) which will not be supported in .NET Core. I do not know whether they will eventually port it if ever. But right now it is a major blocker for a project like that from using .NET Core because of lack of TypeLib support compared to .NET Fx. 

To use it effectively as a part of build task and minimizing dependencies on resources like `TypeLibConverter`, we're talking about broadening the olewoo's scope from just a type library viewer to something more like automatic IDL generator (hopefully that's more smarter than what .NET Fx does and works with .NET Core). 

Is that what you had in mind for using olewoo in a build process? Or would the nuget package be mainly used as part of command-line batch script called during build instead?

**Comment by drmason789** [comment]
I develop a commercial Excel add-in which exposes a few 10s of functions to the user though a COM API. I don't like how tlbexp adapts the C# namespaces to the COM namespace, and changes references to other type libraries.

I was very happy to find olewoo because I can have oledump dump the tlb generated by tlbexp to IDL, perform some regex replacements, then use MIDL to build the tlb with the namespaces I want, and refer to the type libraries I intended.

So I would perhaps just have a olewoo.oledump nuget package that nuget would install in the %userprofile%\.nuget\packages\olewoo.oledump folder, and my build script would run it from there instead of including the executable in the project. 

I'm not sure the benefit of having the UI tool in a nuget package. 

Another thing that could be made is a Windows Installer XML project to create an msi to install all of olewoo in the  Program FIles folder and set up the PATH so that it's available on the command line.

This is something I can do. Does this sound good to you?

**Comment by bclothier** [comment]
I agree UI in a nuget doesn't make sense. Using it as as external build tool via script also should avoid the problem of matching the bitness. However, as noted, it need to be documented that it relies on C++ build tools in order to use the MIDL compiler to act on modified IDL files. On a workstation that doesn't have C++ development installed, the build step would not be that useful.

The idea of decoupling it from the C++ build tools completely would be a major revision and probably needs its own PR anyway.

**Comment by drmason789** [comment]
I haven't forgotten this - I'm preoccupied with work lately.
